# Generated by Django 4.1 on 2022-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=20)),
                ('device_type', models.CharField(choices=[('Desktop', 'Desktop'), ('Laptop', 'Laptop'), ('Mobile', 'Mobile')], default='Desktop', max_length=20)),
                ('order_type', models.CharField(choices=[('Order', 'Order'), ('Notify', 'Notify'), ('Book', 'Book')], default='Order', max_length=20)),
            ],
        ),
    ]
