# Generated by Django 4.1 on 2022-08-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=1)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Available', 'Available'), ('Restocking', 'Restocking')], default='Sold', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=1)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Available', 'Available'), ('Restocking', 'Restocking')], default='Sold', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=1)),
                ('issues', models.CharField(default='No issues', max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Sold', 'Sold'), ('Available', 'Available'), ('Restocking', 'Restocking')], default='Sold', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
